schema_version = "1.0.0"

id = "rendercue"
version = "1.0.1"
name = "RenderCue"
tagline = "Sequence. Queue. Render"
maintainer = "Usama Bin Shahid"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/usamasq/RenderCue"
tags = ["Render", "Pipeline"]

blender_version_min = "4.2.0"

# Permissions
[permissions]
files = "Save renders to user-defined directories"
network = "Send render notifications via Webhooks"

