schema_version = "1.0.0"

id = "rendercue"
version = "1.0.0"
name = "RenderCue"
tagline = "Sequence. Queue. Render"
maintainer = "Usama Bin Shahid"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/usamasq/RenderCue"
tags = ["Render", "Pipeline"]

blender_version_min = "4.2.0"

# Permissions
[permissions]
files = "Needed to save rendered images and video files to arbitrary user-defined output directories outside the blend file location"
network = "Required to send render completion notifications to user-configured Webhook URLs (e.g., Discord, Slack)"

